### ISSUE TITLE
document why we want ubuntu mate for raspberry pi

### ISSUE THREAD

**Issue by adampbeardsley** [adampbeardsley/CHART#10]
@dannyjacobs's class was trying to install our setup and ran into some issues:

>Here are the major errors we keep running into when trying to execute the blocks generated by gnu companion.

> “Warning: failed to XInitThreads()
> Linux; GNU C++ version 6.2.0 20161010; Boost_106100; UHD_003.009.005-0-unknown”

> Gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.10
>Built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy soapy redpitaya

It looks like it's because they're using Raspbian. We need to document better why we don't use raspbian, and preferably actually understand _why_ first.

**Comment by bryanna111** [comment]
I resolved this by including a write up in the tutorials section of the google drive. I talked to Edgar and he said that it just kept popping up with an error message when using Raspbian that I included in the report, but after much research into both operating systems I can't articulate past that why the error message was displaying.
