### ISSUE TITLE
soapysdr not available 

### ISSUE THREAD

**Issue by dannyjacobs** [adampbeardsley/CHART#12]
When doing step one on Ubuntu MATE 16.04 soapy-sdr is not found in aptitude.

**Comment by adampbeardsley** [comment]
It turns out CHART never actually used soapy - we had it when we were using virtual machines, but it never installed on the pi. Should be able to proceed without it.

**Comment by adampbeardsley** [comment]
oops... I should remove it from the instructions before closing.
